// Modelo del catálogo ampliado de Platanitos (500 productos) usado por
// `npm run db:catalog` y `npm run db:catalog:sql`.
//
// Se construyó a partir de información pública de platanitos.com (octubre 2026):
//   - Departamentos, categorías y tipos de producto: sitemaps públicos
//     /pe/sitemap/category-0.xml y products-0..2.xml (permitidos en robots.txt).
//   - Marcas más frecuentes: /pe/sitemap/brand-0.xml.
//   - Rangos de precio (PEN): datos estructurados JSON-LD de fichas de producto.
// No se copian fichas reales: cada producto se genera combinando estas plantillas
// (tipo + público + modelo + color), con el estilo de nombre de la tienda:
// "{Tipo} {Público} {Modelo}", por ejemplo "Zapatillas Urbanas Unisex Old Skool".
//
// Patrones de modelo: '#' dígito 0-9, '%' dígito 1-9, '@' letra mayúscula,
// '{w}' nombre de la lista MODEL_WORDS y '{p}' prefijo de la plantilla.

export const CATALOG_SIZE = 500;
export const SEED = 20261008;

export const IMAGES = {
  urbanas1: 'photo-1525966222134-fcfa99b8ae77',
  urbanas2: 'photo-1549298916-b41d501d3772',
  urbanas3: 'photo-1514989940723-e8e51635b782',
  urbanas4: 'photo-1560769629-975ec94e6a86',
  running1: 'photo-1542291026-7eec264c27ff',
  running2: 'photo-1600185365483-26d7a4cc7519',
  running3: 'photo-1606107557195-0e29a4b5b4aa',
  pastel: 'photo-1595950653106-6c9ebd614d3a',
  tacos1: 'photo-1543163521-1bf539c55dd2',
  tacos2: 'photo-1591884807537-0bce39888fe0',
  tacos3: 'photo-1535043934128-cf0b28d52f95',
  botin: 'photo-1605732440685-d0654d81aa30',
  botasOutdoor: 'photo-1520639888713-7851133b1ed0',
  cuero: 'photo-1614252235316-8c857d38b5f4',
  sandalias1: 'photo-1562273138-f46be4ebdf33',
  sandalias2: 'photo-1603487742131-4160ec999306',
  ropa: 'photo-1490481651871-ab68de25d43d',
  polo1: 'photo-1521572163474-6864f9cf17ab',
  polo2: 'photo-1571945153237-4929e783af4a',
  polo3: 'photo-1576566588028-4147f3842f27',
  polo4: 'photo-1586363104862-3a5e2ab60d99',
  polera: 'photo-1556821840-3a63f95609a7',
  jeans: 'photo-1542272604-787c3835535d',
  chinos: 'photo-1473966968600-fa801b869a1a',
  joggers: 'photo-1506629082955-511b1aa562c8',
  vestido: 'photo-1595777457583-95e059d581b8',
  blusa: 'photo-1564257631407-4deb1f99d992',
  camisaDenim: 'photo-1596755094514-f87e34085b2c',
  casacaCuero: 'photo-1551028719-00167b16eac5',
  abrigo: 'photo-1539533018447-63fcce2678e3',
  short: 'photo-1591195853828-11db59a44f6b',
  falda: 'photo-1583496661160-fb5886a0aaaa',
  medias: 'photo-1586350977771-b3b0abd50c82',
  ninos1: 'photo-1503919545889-aef636e10ad4',
  ninos2: 'photo-1631947430066-48c30d57b943',
  bebe: 'photo-1515488042361-ee00e0ddd4e4',
  mochila: 'photo-1553062407-98eeb64c6a62',
  cartera: 'photo-1584917865442-de89df76afd3',
  reloj: 'photo-1524592094714-0f0654e20314',
  smartwatch: 'photo-1523275335684-37898b6baf30',
  joyeria1: 'photo-1515562141207-7a88fb7ce338',
  joyeria2: 'photo-1535632066927-ab7c9ab60908',
  lentes: 'photo-1572635196237-14b3f281503f',
  gorra: 'photo-1588850561407-ed78c282e89b',
  correa: 'photo-1624222247344-550fb60583dc',
  billetera: 'photo-1627123424574-724758594e93',
  audifonos1: 'photo-1505740420928-5e560c06d30e',
  audifonos2: 'photo-1583394838336-acd977736f90',
  smartphone: 'photo-1601784551446-20c9e07cdbdb',
  electro: 'photo-1570222094114-d054a817e56b',
  cocina: 'photo-1610701596007-11502861dcfa',
  sofa: 'photo-1555041469-a586c61ea9bc',
  sala: 'photo-1513694203232-719a280e022f',
  silla: 'photo-1592078615290-033ee584e267',
  lampara: 'photo-1507473885765-e6ed057f782c',
  dormitorio: 'photo-1522771739844-6a9f6d5f14af',
  juguetes: 'photo-1558060370-d644479cb6f7',
  juegoMesa: 'photo-1606503153255-59d8b8b82176',
  libro: 'photo-1544947950-fa07a98d237f',
  cuaderno: 'photo-1531346878377-a5be20888e57',
  plumones: 'photo-1456735190827-d1262f71b8a3',
  gym: 'photo-1517836357463-d25dfeac3438',
  yoga: 'photo-1601925260368-ae2f83cf8b7f',
  pelota: 'photo-1579952363873-27f3bade9f55',
  tomatodo: 'photo-1602143407151-7111542de6e8',
  skincare: 'photo-1556228578-8c89e6adf883',
  shampoo: 'photo-1535585209827-a15fcdbc4c2d',
  labial: 'photo-1586495777744-4413f21062fa',
  brochas: 'photo-1596462502278-27bfdc403348',
  vino: 'photo-1510812431401-41d2bd2722f3',
  licor: 'photo-1569529465841-dfecdab7503b',
  snacks: 'photo-1511381939415-e44015466834',
  mascotas: 'photo-1583337130417-3346a1be7dee',
  maleta: 'photo-1565026057447-bc90a3dceb87',
};

export const imageUrl = (key) => `https://images.unsplash.com/${IMAGES[key]}?fit=crop&q=85&w=800`;

// tier: 1 = económica, 2 = intermedia, 3 = premium (ubica el precio dentro del rango).
// dama: la tienda usa "Dama" en lugar de "Mujer" en los nombres de esa marca.
export const BRANDS = {
  Nike: { tier: 3 },
  Adidas: { tier: 3 },
  Puma: { tier: 2 },
  Vans: { tier: 3 },
  Converse: { tier: 3 },
  'New Balance': { tier: 3 },
  Reebok: { tier: 2 },
  Skechers: { tier: 2 },
  Fila: { tier: 2 },
  Kappa: { tier: 2 },
  Umbro: { tier: 2 },
  Asics: { tier: 3 },
  'Under Armour': { tier: 3 },
  'The North Face': { tier: 3 },
  Merrell: { tier: 3 },
  CAT: { tier: 3 },
  'Hi-Tec': { tier: 2 },
  'Discovery Expedition': { tier: 2 },
  Crocs: { tier: 3 },
  Ecco: { tier: 3, models: ['{w}0%'] },
  Bellucci: { tier: 2, models: ['Mod. {w}'] },
  Lumberjack: { tier: 2, models: ['{w}', '0#####'] },
  Avia: { tier: 1, models: ['12-######'] },
  Apolo: { tier: 2, models: ['AH2#-##'] },
  Kaida: { tier: 2, models: ['KD2#-0#'] },
  Patrick: { tier: 2 },
  Kelme: { tier: 1 },
  Walking: { tier: 1 },
  Coritex: { tier: 1, models: ['C-###'] },
  'Ocean Pacific': { tier: 1, models: ['{w}', '{w}-H2#'] },
  Tapout: { tier: 1 },
  Kansas: { tier: 2 },
  Platanitos: { tier: 1, models: ['{p} {w}'], dama: true },
  'Platanitos Life': { tier: 1 },
  Impuls: { tier: 1, models: ['{w}0%'] },
  Aranni: { tier: 2, dama: true },
  'Beira Rio': { tier: 2, models: ['4###.###'] },
  Vizzano: { tier: 2, models: ['1###.###'] },
  Molekinha: { tier: 1, models: ['2###.###'] },
  Zaxy: { tier: 1 },
  Zohar: { tier: 1 },
  Chabely: { tier: 1 },
  Limoni: { tier: 1, dama: true },
  Just4U: { tier: 1 },
  'Expo Punto': { tier: 1 },
  'Urpi Dreams': { tier: 2 },
  'Cottons Jeans': { tier: 2 },
  'Fordan Jeans': { tier: 2, models: ['0###', '3###'] },
  Kayser: { tier: 1, models: ['##.####'] },
  Colloky: { tier: 1 },
  'Warner Bros': { tier: 2, models: ['Looney Tunes', 'Batman', 'Superman', 'Harry Potter', 'Tom y Jerry', 'Mujer Maravilla'] },
  Speedo: { tier: 2 },
  Guess: { tier: 3 },
  Amphora: { tier: 2 },
  Ziol: { tier: 1 },
  Himawari: { tier: 1, models: ['H####', 'H###'] },
  'Bubba Bags': { tier: 2 },
  Scool: { tier: 1 },
  Samsonite: { tier: 3 },
  Skmei: { tier: 1, models: ['1###'] },
  Lenovo: { tier: 2 },
  i2go: { tier: 1 },
  Kingmax: { tier: 2, models: ['KM-####', 'JH-###'] },
  Hush: { tier: 2, models: ['HU-##@'] },
  Ichimatsu: { tier: 1 },
  Tuhome: { tier: 2 },
  'Flying Tiger': { tier: 1, models: ['30#####'] },
  'Fisher Price': { tier: 2 },
  'X-Shot': { tier: 2 },
  Panini: { tier: 2 },
  'Faber-Castell': { tier: 2 },
  Stabilo: { tier: 2 },
  Maybelline: { tier: 2 },
  Coquette: { tier: 1 },
  'Be Natural': { tier: 1 },
  Lotte: { tier: 1 },
  Nongshim: { tier: 1 },
  Tabernero: { tier: 2 },
  'La Caravedo': { tier: 3 },
  Wilson: { tier: 2 },
  Workout: { tier: 1 },
  'Sundara Joyas': { tier: 1, models: ['SUN000###'] },
};

export const MODEL_WORDS = [
  'Aroa', 'Yara', 'Tayra', 'Ibiza', 'Valle', 'Artika', 'Milán', 'Siena', 'Paracas', 'Máncora',
  'Colca', 'Nazca', 'Inti', 'Killa', 'Luna', 'Coral', 'Bruma', 'Nova', 'Alma', 'Brisa',
  'Dana', 'Elena', 'Fiora', 'Gala', 'Iris', 'Jade', 'Kira', 'Mara', 'Nara', 'Olivia',
  'Rubí', 'Tiara', 'Vera', 'Zoe', 'Andes', 'Pisac', 'Sora', 'Capri', 'Roma', 'Viena',
  'Bruno', 'Dante', 'Thiago', 'Marco', 'Lucca', 'Mateo', 'Enzo', 'Gael', 'Leo', 'Iker',
  'Aurora', 'Celeste', 'Delta', 'Ébano', 'Flora', 'Habana', 'Lirio', 'Malva', 'Oasis', 'Sahara',
];

// Colores con el formato del seed (primera letra en mayúscula). Los repetidos
// pesan más, siguiendo la frecuencia observada en los slugs de la tienda.
const SHOE_COLORS = ['Negro', 'Negro', 'Negro', 'Blanco', 'Blanco', 'Azul', 'Gris', 'Beige', 'Rosado', 'Verde', 'Rojo', 'Marrón', 'Celeste'];
const WOMEN_SHOE_COLORS = ['Negro', 'Negro', 'Camel', 'Beige', 'Nude', 'Marrón', 'Blanco', 'Dorado', 'Plata', 'Rojo', 'Vino'];
const LEATHER_COLORS = ['Negro', 'Negro', 'Marrón', 'Marrón', 'Camel', 'Vino'];
const APPAREL_COLORS = ['Negro', 'Negro', 'Blanco', 'Azul', 'Gris', 'Beige', 'Verde', 'Rosado', 'Celeste', 'Rojo', 'Plomo', 'Azul marino'];
const WOMEN_APPAREL_COLORS = ['Negro', 'Blanco', 'Rosado', 'Lila', 'Fucsia', 'Beige', 'Celeste', 'Verde', 'Coral', 'Crema', 'Multicolor'];
const DENIM_COLORS = ['Azul', 'Azul', 'Celeste', 'Negro', 'Jean', 'Gris'];
const KIDS_COLORS = ['Rosado', 'Celeste', 'Azul', 'Amarillo', 'Lila', 'Verde', 'Rojo', 'Multicolor', 'Blanco'];
const BAG_COLORS = ['Negro', 'Negro', 'Camel', 'Beige', 'Marrón', 'Blanco', 'Rosado', 'Vino', 'Verde', 'Plata', 'Dorado'];
const SPORT_COLORS = ['Negro', 'Negro', 'Azul', 'Gris', 'Rojo', 'Verde', 'Naranja', 'Blanco'];
const ITEM_COLORS = ['Negro', 'Blanco', 'Gris', 'Azul', 'Rosado', 'Verde', 'Beige'];
const VARIOUS = ['Varios', 'Multicolor'];
const NO_COLOR = ['Sin color'];

export const FEATURES = {
  calzado: [
    'Plantilla acolchada que brinda comodidad durante todo el día.',
    'Suela de caucho antideslizante con buen agarre.',
    'Capellada de material sintético fácil de limpiar.',
    'Diseño ligero y flexible.',
    'Costuras reforzadas para mayor durabilidad.',
    'Forro textil transpirable.',
  ],
  ropa: [
    'Tela suave al tacto y de secado rápido.',
    'Corte cómodo que acompaña el movimiento.',
    'Costuras reforzadas que mantienen la forma tras cada lavado.',
    'Fácil de combinar con el resto de tu clóset.',
    'Lavar a máquina con colores similares.',
  ],
  bolsos: [
    'Compartimento principal con cierre y bolsillo interior.',
    'Acabado resistente al uso diario.',
    'Correa ajustable para llevarlo como prefieras.',
    'Herrajes metálicos de larga duración.',
  ],
  accesorios: [
    'Acabado cuidado que eleva cualquier look.',
    'Ligero y cómodo de llevar todo el día.',
    'Ideal para regalar.',
    'Incluye empaque de la marca.',
  ],
  deporte: [
    'Materiales resistentes para entrenamientos intensos.',
    'Pensado para rendir en cada sesión.',
    'Fácil de transportar y guardar.',
  ],
  tecnologia: [
    'Compatible con la mayoría de smartphones.',
    'Incluye cable de carga.',
    'Garantía de 6 meses.',
    'Diseño compacto y liviano.',
  ],
  hogar: [
    'Materiales de calidad pensados para el uso diario.',
    'Fácil de limpiar.',
    'Combina con distintos estilos de decoración.',
    'Producto con garantía de la marca.',
  ],
  juguetes: [
    'Estimula la creatividad y la imaginación.',
    'Materiales seguros y resistentes.',
    'Ideal para jugar en familia.',
  ],
  libros: [
    'Edición en español.',
    'Encuadernación rústica a color.',
    'Ideal para coleccionistas.',
  ],
  utiles: [
    'Ideal para el colegio, la universidad o la oficina.',
    'Colores intensos y duraderos.',
    'Materiales no tóxicos.',
  ],
  belleza: [
    'Dermatológicamente probado.',
    'Fórmula de larga duración.',
    'Apto para uso diario.',
  ],
  abarrotes: [
    'Producto importado.',
    'Ideal para compartir.',
    'Conservar en un lugar fresco y seco.',
  ],
  bebida: [
    'Venta exclusiva para mayores de 18 años.',
    'Servir a la temperatura recomendada.',
    'Tomar bebidas alcohólicas en exceso es dañino.',
  ],
  bebes: [
    'Algodón suave que cuida la piel del bebé.',
    'Broches que facilitan el cambio de pañal.',
    'Lavar con jabón neutro.',
  ],
  equipaje: [
    'Ruedas de giro 360° y asa telescópica.',
    'Cierres resistentes y forro interior.',
    'Liviana y fácil de maniobrar.',
  ],
  mascotas: [
    'Materiales seguros para tu mascota.',
    'Fácil de limpiar.',
    'Diseño resistente a mordidas.',
  ],
};

// Cada plantilla define una familia de productos: categoría, tipos de nombre,
// públicos, marcas (con líneas reales cuando la marca es conocida), rango de
// precio en soles, esquema de tallas, colores, imágenes y peso relativo dentro
// del catálogo (los pesos se normalizan a exactamente CATALOG_SIZE productos).
//
// sizes: 'shoe' (EUR según público), 'apparel' (ALPHA), 'baby' (ALPHA por meses),
// 'one' (ONE_SIZE "Única"). brandPrice: rango propio para marcas muy distintas
// al resto de la plantilla (reemplaza al nivel de la marca).
export const TEMPLATES = [
  // ---------------------------------------------------------------- Calzado
  {
    key: 'zapatillas-urbanas', family: 'calzado', category: 'Zapatillas urbanas', weight: 40,
    types: ['Zapatillas Urbanas'], genders: ['Hombre', 'Mujer', 'Unisex'],
    brands: ['Nike', 'Adidas', 'Puma', 'Vans', 'Converse', 'New Balance', 'Reebok', 'Skechers', 'Fila', 'Kappa', 'Umbro', 'Ocean Pacific', 'Avia', 'Lumberjack'],
    models: {
      Nike: ['Court Vision Low', 'Air Max SC', 'Tanjun', 'Court Royale 2', 'Venture Runner', 'Full Force Low'],
      Adidas: ['Grand Court 2.0', 'Breaknet 2.0', 'Advantage 2.0', 'VL Court 3.0', 'Hoops 3.0'],
      Puma: ['Caven 2.0', 'Carina 2.0', 'Smash 3.0', 'Shuffle', 'Rebound V6 Low'],
      Vans: ['Old Skool', 'Sk8-Low', 'Slip-On', 'Authentic', 'Ward'],
      Converse: ['Chuck Taylor All Star', 'Chuck Taylor Lift', 'Run Star Motion'],
      'New Balance': ['237', '574', '327', '515'],
      Reebok: ['Club C 85', 'Classic Leather', 'Royal Complete'],
      Skechers: ['Uno', 'Court Classics', "D'Lites"],
      Fila: ['Disruptor II', 'Ray Tracer'],
      Kappa: ['Authentic Logo', 'Bash'],
      Umbro: ['Speciali Terrace 100', 'Fusion Lite'],
    },
    price: [89.9, 399.9], sizes: 'shoe', colors: SHOE_COLORS,
    images: ['urbanas1', 'urbanas2', 'urbanas3', 'urbanas4'],
    about: 'de estilo urbano para usar todos los días',
  },
  {
    key: 'zapatillas-running', family: 'calzado', category: 'Zapatillas running', weight: 22,
    types: ['Zapatillas Running'], genders: ['Hombre', 'Mujer'],
    brands: ['Nike', 'Adidas', 'Puma', 'Asics', 'Under Armour', 'New Balance', 'Skechers', 'Reebok', 'Apolo', 'Kaida'],
    models: {
      Nike: ['Revolution 7', 'Downshifter 13', 'Pegasus 41', 'Winflo 11'],
      Adidas: ['Runfalcon 3.0', 'Duramo SL', 'Galaxy 7', 'Ultrabounce'],
      Puma: ['Velocity Nitro 3', 'Electrify Nitro 3', 'Transport'],
      Asics: ['Gel-Contend 9', 'Gel-Excite 10', 'Jolt 4'],
      'Under Armour': ['Charged Assert 10', 'Charged Pursuit 3'],
      'New Balance': ['Fresh Foam 680', '520 v8'],
      Skechers: ['Go Run Consistent', 'Max Cushioning'],
      Reebok: ['Floatride Energy 5', 'Energen Lux'],
    },
    price: [159.9, 499.9], sizes: 'shoe', colors: SPORT_COLORS,
    images: ['running1', 'running2', 'running3'],
    about: 'con amortiguación para correr en pista o en la ciudad',
  },
  {
    key: 'zapatillas-futbol', family: 'calzado', category: 'Zapatillas de fútbol', weight: 16,
    types: ['Zapatillas de Fútbol'], genders: ['Hombre', 'Hombre', 'Niño', 'Unisex'],
    brands: ['Nike', 'Adidas', 'Puma', 'Umbro', 'Patrick', 'Kelme', 'Kappa'],
    models: {
      Nike: ['Phantom GX Club TF', 'Mercurial Vapor 15 Club', 'Tiempo Legend 10 Club'],
      Adidas: ['Predator Club TF', 'Copa Pure 2 Club', 'X Crazyfast Club'],
      Puma: ['Future 7 Play', 'Ultra 5 Play'],
      Umbro: ['Velocita Club', 'Tocco Club'],
      Patrick: ['Raptor', 'Dybala', 'Strike TF'],
      Kelme: ['Precision TF', 'Pulse'],
    },
    price: [95.9, 349.9], sizes: 'shoe', colors: SPORT_COLORS,
    images: ['running2', 'running3'],
    about: 'para canchas sintéticas con tapones de goma',
  },
  {
    key: 'zapatillas-training', family: 'calzado', category: 'Zapatillas training', weight: 8,
    types: ['Zapatillas Training'], genders: ['Hombre', 'Mujer'],
    brands: ['Reebok', 'Tapout', 'Under Armour', 'Nike', 'Skechers'],
    models: {
      Reebok: ['Flexagon Force 4', 'Nanoflex TR 2'],
      'Under Armour': ['Charged Commit TR 4'],
      Nike: ['MC Trainer 3', 'Legend Essential 3'],
      Skechers: ['Go Walk Joy', 'Go Walk 7'],
    },
    price: [119.9, 329.9], sizes: 'shoe', colors: SPORT_COLORS,
    images: ['running1', 'running3'],
    about: 'estables y versátiles para el gimnasio',
  },
  {
    key: 'zapatillas-outdoor', family: 'calzado', category: 'Zapatillas outdoor', weight: 12,
    types: ['Zapatillas Outdoor'], genders: ['Hombre', 'Mujer'],
    brands: ['The North Face', 'Merrell', 'CAT', 'Hi-Tec', 'Discovery Expedition', 'Under Armour'],
    models: {
      'The North Face': ['Cragmont WP', 'Vectiv Exploris', 'Hedgehog 3'],
      Merrell: ['Moab 3', 'Accentor 3'],
      CAT: ['Threshold', 'Invader'],
      'Hi-Tec': ['Altitude X-Plorer', 'V-Lite'],
      'Discovery Expedition': ['Seward', 'Kodiak'],
      'Under Armour': ['Charged Maven Trail'],
    },
    price: [139.9, 549.9], sizes: 'shoe', colors: ['Negro', 'Gris', 'Marrón', 'Verde', 'Beige', 'Azul'],
    images: ['botasOutdoor', 'running2'],
    about: 'con suela de tracción para trekking y caminatas',
  },
  {
    key: 'zapatillas-escolares', family: 'calzado', category: 'Zapatillas escolares', weight: 8,
    types: ['Zapatillas Escolares', 'Zapatillas Escolares de Cuero'], genders: ['Niño', 'Niña', 'Juvenil'],
    brands: ['Skechers', 'Kaida', 'Walking', 'Coritex'],
    models: { Skechers: ['Quick Street', 'Dyna-Lite'] },
    price: [59.9, 209.9], sizes: 'shoe', colors: ['Negro', 'Negro', 'Negro', 'Blanco'],
    images: ['urbanas3', 'urbanas2'],
    about: 'resistentes para el uso escolar diario',
  },
  {
    key: 'sandalias', family: 'calzado', category: 'Sandalias', weight: 24,
    types: ['Sandalias', 'Sandalias Taco Cuña', 'Sandalias Planas', 'Sandalias Tijera'], genders: ['Mujer'],
    brands: ['Platanitos', 'Impuls', 'Aranni', 'Beira Rio', 'Molekinha', 'Zaxy', 'Vizzano', 'Zohar', 'Chabely'],
    prefix: 'Sv', price: [39.9, 149.9], sizes: 'shoe', colors: WOMEN_SHOE_COLORS,
    images: ['sandalias1', 'sandalias2'],
    about: 'frescas y cómodas para la temporada de calor',
  },
  {
    key: 'sandalias-slide', family: 'calzado', category: 'Sandalias', weight: 6,
    types: ['Sandalias Tipo Slide'], genders: ['Unisex'],
    brands: ['Adidas', 'Nike', 'Reebok', 'Puma', 'Crocs'],
    models: {
      Adidas: ['Adilette Aqua', 'Adilette Shower'],
      Nike: ['Victori One', 'Calm Slide'],
      Reebok: ['Classic Clean Slide'],
      Puma: ['Popcat 20', 'Leadcat 2.0'],
      Crocs: ['Classic Slide'],
    },
    price: [39.9, 199.9], sizes: 'shoe', colors: ['Negro', 'Negro', 'Blanco', 'Azul', 'Gris', 'Beige'],
    images: ['sandalias2', 'sandalias1'],
    about: 'livianas para la playa, la piscina o la casa',
  },
  {
    key: 'botines-mujer', family: 'calzado', category: 'Botas y botines', weight: 14,
    types: ['Botín', 'Botas', 'Botín Casual'], genders: ['Mujer'],
    brands: ['Platanitos', 'Vizzano', 'Beira Rio', 'Aranni', 'Impuls', 'Zohar'],
    prefix: 'Bt', price: [89.9, 259.9], sizes: 'shoe', colors: WOMEN_SHOE_COLORS,
    images: ['botin', 'tacos3'],
    about: 'con caña media que abriga y estiliza',
  },
  {
    key: 'botines-hombre', family: 'calzado', category: 'Botas y botines', weight: 4,
    types: ['Botín', 'Botas de Cuero'], genders: ['Hombre'],
    brands: ['CAT', 'Lumberjack', 'Hi-Tec', 'Apolo'],
    models: { CAT: ['Colorado 2.0', 'Second Shift', 'Founder'] },
    price: [149.9, 499.9], sizes: 'shoe', colors: LEATHER_COLORS,
    images: ['botasOutdoor', 'botin'],
    about: 'de cuero con suela robusta',
  },
  {
    key: 'vestir-mujer', family: 'calzado', category: 'Calzado de vestir', weight: 11,
    types: ['Calzado Vestir', 'Zapatos de Taco', 'Stilettos', 'Zapatos Taco Bloque'], genders: ['Mujer'],
    brands: ['Platanitos', 'Ecco', 'Vizzano', 'Beira Rio', 'Impuls'],
    prefix: 'Cv', price: [59.9, 249.9], sizes: 'shoe', colors: WOMEN_SHOE_COLORS,
    images: ['tacos1', 'tacos2', 'tacos3'],
    about: 'elegantes para la oficina o una ocasión especial',
  },
  {
    key: 'vestir-hombre', family: 'calzado', category: 'Calzado de vestir', weight: 5,
    types: ['Zapatos de Vestir', 'Zapatos Oxford'], genders: ['Hombre'],
    brands: ['Bellucci', 'Ecco', 'Platanitos'],
    prefix: 'Cv', price: [129.9, 399.9], sizes: 'shoe', colors: LEATHER_COLORS,
    images: ['cuero'],
    about: 'de cuero con acabado pulido',
  },
  {
    key: 'mocasines', family: 'calzado', category: 'Mocasines', weight: 10,
    types: ['Mocasín', 'Mocasín Casual'], genders: ['Mujer', 'Hombre'],
    brands: ['Ecco', 'Bellucci', 'Platanitos', 'Vizzano', 'Beira Rio'],
    prefix: 'Moc', price: [65.9, 299.9], sizes: 'shoe', colors: LEATHER_COLORS,
    images: ['cuero', 'tacos2'],
    about: 'sin pasadores, fáciles de poner y quitar',
  },
  {
    key: 'zuecos', family: 'calzado', category: 'Zuecos', weight: 6,
    types: ['Zuecos'], genders: ['Unisex', 'Mujer', 'Niño', 'Niña'],
    brands: ['Crocs'],
    models: { Crocs: ['Classic Clog', 'Bayaband Clog', 'Crocband Clog', 'Classic Platform Clog', 'Echo Clog'] },
    price: [129.9, 279.9], sizes: 'shoe', colors: ['Negro', 'Blanco', 'Celeste', 'Rosado', 'Verde', 'Lila', 'Amarillo'],
    images: ['sandalias2'],
    about: 'livianos y lavables con correa trasera',
  },
  {
    key: 'pantuflas', family: 'calzado', category: 'Pantuflas', weight: 4,
    types: ['Pantufla'], genders: ['Mujer', 'Unisex'],
    brands: ['Platanitos'],
    prefix: 'P', price: [19.9, 49.9], sizes: 'shoe', colors: ['Rosado', 'Gris', 'Lila', 'Beige', 'Celeste'],
    images: ['pastel'],
    about: 'suaves y abrigadoras para estar en casa',
  },
  {
    key: 'ballerinas', family: 'calzado', category: 'Ballerinas', weight: 4,
    types: ['Ballerina'], genders: ['Mujer'],
    brands: ['Vizzano', 'Beira Rio', 'Molekinha'],
    price: [59.9, 139.9], sizes: 'shoe', colors: WOMEN_SHOE_COLORS,
    images: ['tacos2', 'tacos1'],
    about: 'planas y versátiles',
  },
  {
    key: 'calzado-infantil', family: 'calzado', category: 'Calzado infantil', weight: 14,
    types: ['Zapatillas Kids', 'Zapatillas Urbanas', 'Zapatillas con Luces', 'Sandalias'], genders: ['Niño', 'Niña'],
    brands: ['Nike', 'Adidas', 'Skechers', 'Colloky', 'Fila', 'Puma'],
    models: {
      Nike: ['Revolution 7 PSV', 'Court Borough Low'],
      Adidas: ['Tensaur Run', 'Grand Court 2.0 K'],
      Skechers: ['S Lights', 'Twinkle Toes'],
      Puma: ['Courtflex V3', 'Smash 3.0 Jr'],
    },
    price: [69.9, 229.9], sizes: 'shoe', colors: KIDS_COLORS,
    images: ['pastel', 'urbanas4', 'ninos2'],
    about: 'con cierre práctico para que los más pequeños se calcen solos',
  },

  // ---------------------------------------------------------------- Ropa
  {
    key: 'polos', family: 'ropa', category: 'Polos', weight: 18,
    types: ['Polo Training', 'Polo Urbano Manga Corta', 'Polo Manga Larga', 'Polo Básico'], genders: ['Hombre', 'Mujer', 'Unisex'],
    brands: ['Nike', 'Adidas', 'Puma', 'Under Armour', 'Reebok', 'Tapout', 'Ocean Pacific', 'Kappa', 'Expo Punto', 'Urpi Dreams', 'Just4U', 'Umbro'],
    models: {
      Nike: ['Dri-FIT Legend', 'Sportswear Club', 'Park VII'],
      Adidas: ['Essentials 3 Stripes', 'Own The Run', 'Train Essentials'],
      Puma: ['ESS Logo', 'Graphics Tee'],
      'Under Armour': ['Tech 2.0', 'HeatGear Armour'],
    },
    price: [39.9, 149.9], sizes: 'apparel', colors: APPAREL_COLORS,
    images: ['polo1', 'polo2', 'polo3', 'polo4'],
    about: 'de algodón y corte regular',
  },
  {
    key: 'poleras', family: 'ropa', category: 'Poleras', weight: 12,
    types: ['Polera Urbana', 'Polera con Capucha', 'Polerón'], genders: ['Hombre', 'Mujer', 'Unisex'],
    brands: ['Nike', 'Adidas', 'Puma', 'Under Armour', 'Kappa', 'Urpi Dreams', 'Expo Punto', 'Ocean Pacific', 'Tapout'],
    models: {
      Nike: ['Club Fleece', 'Sportswear Essential'],
      Adidas: ['Essentials Fleece', 'Trefoil Hoodie'],
      'Under Armour': ['Rival Fleece'],
    },
    price: [59.9, 279.9], sizes: 'apparel', colors: APPAREL_COLORS,
    images: ['polera'],
    about: 'de felpa por dentro para los días frescos',
  },
  {
    key: 'pantalones', family: 'ropa', category: 'Pantalones', weight: 10,
    types: ['Pantalón Drill', 'Pantalón Casual', 'Pantalón Jogger', 'Pantalón Palazzo'], genders: ['Mujer', 'Hombre'],
    brands: ['Cottons Jeans', 'Fordan Jeans', 'Kansas', 'Lumberjack'],
    price: [69.9, 179.9], sizes: 'apparel', colors: ['Negro', 'Beige', 'Azul marino', 'Verde', 'Gris', 'Camel'],
    images: ['chinos', 'joggers'],
    about: 'de tiro medio y tela con elasticidad',
  },
  {
    key: 'jeans', family: 'ropa', category: 'Jeans', weight: 14,
    types: ['Jean Skinny', 'Jean Mom', 'Jean Recto', 'Jean Wide Leg', 'Jean Slim'], genders: ['Mujer', 'Hombre'],
    brands: ['Cottons Jeans', 'Fordan Jeans', 'Kansas', 'Lumberjack', 'Guess'],
    price: [59.9, 249.9], sizes: 'apparel', colors: DENIM_COLORS,
    images: ['jeans', 'camisaDenim'],
    about: 'de denim con cinco bolsillos',
  },
  {
    key: 'vestidos', family: 'ropa', category: 'Vestidos', weight: 10,
    types: ['Vestido Midi', 'Vestido Corto', 'Vestido Largo Estampado', 'Vestido Camisero'], genders: ['Mujer'],
    brands: ['Urpi Dreams', 'Cottons Jeans', 'Fordan Jeans', 'Just4U'],
    price: [49.9, 189.9], sizes: 'apparel', colors: WOMEN_APPAREL_COLORS,
    images: ['vestido', 'ropa'],
    about: 'con caída fluida para el día o la noche',
  },
  {
    key: 'blusas', family: 'ropa', category: 'Blusas', weight: 10,
    types: ['Blusa Manga Larga', 'Blusa Casual', 'Blusa Off Shoulder', 'Camisa'], genders: ['Mujer'],
    brands: ['Urpi Dreams', 'Expo Punto', 'Just4U', 'Cottons Jeans', 'Fordan Jeans'],
    price: [39.9, 119.9], sizes: 'apparel', colors: WOMEN_APPAREL_COLORS,
    images: ['blusa', 'camisaDenim'],
    about: 'de tela ligera y corte femenino',
  },
  {
    key: 'casacas', family: 'ropa', category: 'Casacas', weight: 10,
    types: ['Casaca Cortavientos', 'Casaca Acolchada', 'Casaca de Cuero Sintético', 'Casaca Jean', 'Abrigo'], genders: ['Hombre', 'Mujer'],
    brands: ['The North Face', 'Adidas', 'Nike', 'Lumberjack', 'Discovery Expedition', 'Kansas', 'Urpi Dreams', 'Ocean Pacific'],
    models: {
      'The North Face': ['Resolve 2', 'Antora', 'Aconcagua 3'],
      Adidas: ['Essentials Insulated', 'Itavic'],
      Nike: ['Windrunner', 'Sportswear Repel'],
    },
    price: [79.9, 499.9], sizes: 'apparel', colors: ['Negro', 'Negro', 'Azul marino', 'Verde', 'Beige', 'Marrón', 'Gris'],
    images: ['casacaCuero', 'abrigo'],
    about: 'que protege del viento y del frío',
  },
  {
    key: 'shorts', family: 'ropa', category: 'Shorts', weight: 10,
    types: ['Short Running', 'Short Training', 'Short Urbano', 'Short de Baño'], genders: ['Hombre', 'Mujer'],
    brands: ['Nike', 'Adidas', 'Puma', 'Under Armour', 'Speedo', 'Ocean Pacific', 'Umbro', 'Tapout'],
    models: {
      Nike: ['Challenger', 'Club'],
      Adidas: ['Own The Run', 'Essentials Chelsea'],
      'Under Armour': ['Launch', 'Tech Vent'],
    },
    price: [35.9, 129.9], sizes: 'apparel', colors: SPORT_COLORS,
    images: ['short'],
    about: 'con pretina elástica y cordón ajustable',
  },
  {
    key: 'leggings', family: 'ropa', category: 'Leggings', weight: 8,
    types: ['Leggings Training', 'Leggings Tiro Alto', 'Top Training'], genders: ['Mujer'],
    brands: ['Nike', 'Adidas', 'Puma', 'Under Armour', 'Reebok', 'Tapout', 'Kayser'],
    models: { Nike: ['One', 'Dri-FIT Fast'], Adidas: ['Optime', 'Essentials'] },
    price: [39.9, 169.9], sizes: 'apparel', colors: ['Negro', 'Negro', 'Gris', 'Lila', 'Azul marino', 'Verde', 'Rosado'],
    images: ['joggers', 'yoga'],
    about: 'de tela elástica que se adapta a cada movimiento',
  },
  {
    key: 'faldas', family: 'ropa', category: 'Faldas', weight: 5,
    types: ['Falda Midi', 'Falda Short', 'Falda Plisada', 'Falda Jean'], genders: ['Mujer'],
    brands: ['Fordan Jeans', 'Cottons Jeans', 'Urpi Dreams', 'Just4U'],
    price: [29.9, 149.9], sizes: 'apparel', colors: WOMEN_APPAREL_COLORS,
    images: ['falda'],
    about: 'de tiro alto y corte favorecedor',
  },
  {
    key: 'pijamas', family: 'ropa', category: 'Pijamas', weight: 10,
    types: ['Pijama', 'Pijama Polar', 'Pijama Manga Larga'], genders: ['Mujer', 'Hombre', 'Niña', 'Niño'],
    brands: ['Kayser', 'Urpi Dreams', 'Platanitos Life', 'Colloky', 'Warner Bros'],
    models: { Kayser: ['65.####', '66.####'] },
    price: [39.9, 99.9], sizes: 'apparel', colors: ['Rosado', 'Celeste', 'Gris', 'Azul marino', 'Lila', 'Multicolor'],
    images: ['ropa', 'dormitorio'],
    about: 'de dos piezas, suave para dormir cómodo',
  },
  {
    key: 'medias', family: 'ropa', category: 'Ropa interior y medias', weight: 6,
    types: ['Pack 3 Medias de Algodón', 'Medias Deportivas', 'Calcetines Escolares', 'Soquetes'], genders: ['Mujer', 'Hombre', 'Unisex', 'Niño', 'Niña'],
    brands: ['Kayser', 'Nike', 'Adidas', 'Puma', 'Umbro'],
    models: {
      Kayser: ['99.HP####', '99.MP####'],
      Nike: ['Everyday Cushioned'],
      Adidas: ['Cushioned Crew'],
    },
    price: [19.9, 59.9], sizes: 'one', colors: ['Negro', 'Blanco', 'Gris', 'Azul marino', 'Multicolor'],
    images: ['medias'],
    about: 'de algodón con puño elástico',
  },
  {
    key: 'boxer', family: 'ropa', category: 'Ropa interior y medias', weight: 3,
    types: ['Bóxer Algodón', 'Pack 3 Bóxer'], genders: ['Hombre'],
    brands: ['Kayser', 'Ocean Pacific', 'Under Armour'],
    models: { Kayser: ['93.###'], 'Under Armour': ['Tech 6in'] },
    price: [14.9, 99.9], sizes: 'apparel', colors: ['Negro', 'Azul marino', 'Gris', 'Vino', 'Multicolor'],
    images: ['ropa'],
    about: 'con pretina suave que no aprieta',
  },
  {
    key: 'lenceria', family: 'ropa', category: 'Ropa interior y medias', weight: 3,
    types: ['Sostén', 'Pantaleta', 'Top Deportivo'], genders: ['Mujer'],
    brands: ['Kayser', 'Zohar', 'Just4U'],
    models: { Kayser: ['10.###', '14.####'] },
    price: [12.9, 69.9], sizes: 'apparel', colors: ['Negro', 'Blanco', 'Nude', 'Rosado', 'Lila'],
    images: ['ropa'],
    about: 'de microfibra suave y sin costuras visibles',
  },
  {
    key: 'ropa-bano', family: 'ropa', category: 'Ropa de baño', weight: 4,
    types: ['Traje de Baño Entero', 'Bikini', 'Jammer'], genders: ['Mujer', 'Hombre'],
    brands: ['Speedo', 'Kayser', 'Ocean Pacific'],
    models: { Speedo: ['Dive Jammer', 'Endurance+', 'Eco Placement'] },
    price: [29.9, 159.9], sizes: 'apparel', colors: ['Negro', 'Azul', 'Fucsia', 'Coral', 'Turquesa', 'Multicolor'],
    images: ['short', 'ropa'],
    about: 'de secado rápido y resistente al cloro',
  },
  {
    key: 'conjuntos', family: 'ropa', category: 'Conjuntos deportivos', weight: 5,
    types: ['Buzo Deportivo', 'Conjunto Deportivo', 'Conjunto Polar'], genders: ['Hombre', 'Mujer'],
    brands: ['Adidas', 'Nike', 'Puma', 'Kappa', 'Umbro', 'Tapout'],
    models: {
      Adidas: ['Essentials 3 Stripes Tricot', 'Linear Fleece'],
      Nike: ['Club Fleece', 'Academy 23'],
      Puma: ['Baseball Tricot', 'Classic Poly'],
    },
    price: [99.9, 349.9], sizes: 'apparel', colors: ['Negro', 'Azul marino', 'Gris', 'Verde', 'Vino'],
    images: ['joggers', 'ropa'],
    about: 'de casaca y pantalón a juego',
  },
  {
    key: 'ropa-infantil', family: 'ropa', category: 'Ropa infantil', weight: 8,
    types: ['Polo Manga Corta', 'Conjunto', 'Polera', 'Short'], genders: ['Niño', 'Niña'],
    brands: ['Colloky', 'Warner Bros', 'Adidas', 'Nike', 'Platanitos Life'],
    models: { Adidas: ['Essentials Kids'], Nike: ['Sportswear Kids'] },
    price: [29.9, 119.9], sizes: 'apparel', colors: KIDS_COLORS,
    images: ['ninos1', 'ninos2'],
    about: 'de algodón suave y estampados divertidos',
  },

  // ---------------------------------------------------- Bolsos y accesorios
  {
    key: 'carteras', family: 'bolsos', category: 'Carteras', weight: 16,
    types: ['Cartera', 'Cartera de Fiesta', 'Cartera Tipo Bandolera', 'Cartera Tote', 'Cartera Casual'], genders: ['Mujer'], genderInName: false,
    brands: ['Limoni', 'Guess', 'Platanitos', 'Amphora', 'Ziol', 'Chabely', 'Bellucci'],
    models: { Guess: ['Noelle', 'Eco Brenton', 'Izzy', 'Meridian'] },
    price: [49.9, 449.9], sizes: 'one', colors: BAG_COLORS,
    images: ['cartera'],
    about: 'de cuero sintético con acabado texturizado',
  },
  {
    key: 'mochilas', family: 'bolsos', category: 'Mochilas', weight: 14,
    types: ['Mochila Casual', 'Mochila Escolar', 'Mochila Porta Laptop', 'Mochila Viajera'], genders: ['Unisex', 'Unisex', 'Mujer', 'Niño'],
    brands: ['Himawari', 'Bubba Bags', 'Scool', 'Nike', 'Adidas', 'Puma', 'The North Face', 'Under Armour', 'Discovery Expedition'],
    models: {
      Nike: ['Heritage', 'Brasilia 9.5'],
      Adidas: ['Classic Badge of Sport', 'Power VII'],
      Puma: ['Phase', 'Buzz'],
      'The North Face': ['Borealis', 'Jester', 'Recon'],
      'Under Armour': ['Hustle 6.0', 'Halftime'],
    },
    price: [59.9, 399.9], sizes: 'one', colors: ['Negro', 'Negro', 'Azul marino', 'Gris', 'Rosado', 'Verde', 'Lila'],
    images: ['mochila'],
    about: 'con espaldar acolchado y varios compartimentos',
  },
  {
    key: 'morrales', family: 'bolsos', category: 'Bolsos y morrales', weight: 8,
    types: ['Morral', 'Bolso Casual', 'Bolso Deportivo', 'Canguro', 'Bolso Tote'], genders: ['Unisex', 'Hombre', 'Mujer'],
    brands: ['Amphora', 'Lumberjack', 'Bubba Bags', 'Nike', 'Adidas', 'Puma', 'Discovery Expedition', 'Himawari'],
    models: { Nike: ['Gym Club', 'Heritage Crossbody'], Adidas: ['Linear Duffel', 'Essentials Waist Bag'], Puma: ['Challenger Duffel'] },
    price: [35.9, 199.9], sizes: 'one', colors: BAG_COLORS,
    images: ['cartera', 'mochila'],
    about: 'práctico para llevar lo esencial',
  },
  {
    key: 'billeteras', family: 'bolsos', category: 'Billeteras y monederos', weight: 8,
    types: ['Billetera', 'Monedero', 'Billetera de Cuero', 'Tarjetero'], genders: ['Mujer', 'Hombre'],
    brands: ['Limoni', 'Ziol', 'Bellucci', 'Guess', 'Lumberjack', 'Platanitos'],
    price: [29.9, 199.9], sizes: 'one', colors: LEATHER_COLORS.concat(['Rosado', 'Beige']),
    images: ['billetera'],
    about: 'con espacio para tarjetas, billetes y monedas',
  },
  {
    key: 'correas', family: 'accesorios', category: 'Correas y cinturones', weight: 5,
    types: ['Correa de Cuero', 'Correa Casual', 'Cinturón Reversible'], genders: ['Hombre', 'Mujer'],
    brands: ['Bellucci', 'Limoni', 'Lumberjack', 'Platanitos', 'Guess'],
    price: [19.9, 179.9], sizes: 'one', colors: LEATHER_COLORS,
    images: ['correa'],
    about: 'con hebilla metálica y largo ajustable',
  },
  {
    key: 'relojes', family: 'accesorios', category: 'Relojes', weight: 6,
    types: ['Reloj Digital', 'Reloj Análogo', 'Reloj Deportivo'], genders: ['Hombre', 'Mujer', 'Unisex'],
    brands: ['Skmei', 'Guess'],
    models: { Guess: ['GW0###L%', 'GW0###G%'] },
    price: [59.9, 599.9], brandPrice: { Skmei: [59.9, 139.9], Guess: [349.9, 599.9] }, sizes: 'one', colors: ['Negro', 'Plata', 'Dorado', 'Azul', 'Rosado'],
    images: ['reloj'],
    about: 'resistente al agua con correa ajustable',
  },
  {
    key: 'smartwatch', family: 'tecnologia', category: 'Relojes', weight: 2,
    types: ['Smartwatch', 'Reloj Inteligente'], genders: ['Unisex'],
    brands: ['Lenovo', 'i2go'],
    models: { Lenovo: ['Thinkplus Watch S2', 'Watch X'], i2go: ['Fit Pro', 'Active 2'] },
    price: [79.9, 299.9], sizes: 'one', colors: ['Negro', 'Gris', 'Rosado', 'Plata'],
    images: ['smartwatch'],
    about: 'con monitor de ritmo cardiaco y notificaciones',
  },
  {
    key: 'joyeria', family: 'accesorios', category: 'Joyería y accesorios', weight: 6,
    types: ['Collar', 'Aretes', 'Pulsera', 'Anillo', 'Set de Aretes'], genders: ['Mujer'], genderInName: false,
    brands: ['Guess', 'Sundara Joyas', 'Platanitos', 'Limoni'],
    price: [19.9, 249.9], sizes: 'one', colors: ['Dorado', 'Dorado', 'Plata', 'Plata', 'Oro rosa'],
    images: ['joyeria1', 'joyeria2'],
    about: 'de acero inoxidable hipoalergénico',
  },
  {
    key: 'lentes', family: 'accesorios', category: 'Accesorios de moda', weight: 3,
    types: ['Lentes de Sol', 'Lentes de Sol Aviador', 'Lentes de Sol Redondos'], genders: ['Unisex', 'Mujer'],
    brands: ['Guess', 'Platanitos', 'Vans'],
    price: [39.9, 189.9], sizes: 'one', colors: ['Negro', 'Carey', 'Dorado', 'Plata'],
    images: ['lentes'],
    about: 'con protección UV400',
  },
  {
    key: 'gorras', family: 'accesorios', category: 'Accesorios de moda', weight: 5,
    types: ['Gorra', 'Gorro', 'Gorra Trucker'], genders: ['Unisex'],
    brands: ['Nike', 'Adidas', 'The North Face', 'Puma', 'Under Armour', 'Vans'],
    models: { Nike: ['Club Cap', 'Dri-FIT Rise'], Adidas: ['Baseball 3 Stripes'], 'The North Face': ['Mudder Trucker', 'Recycled 66'] },
    price: [39.9, 149.9], sizes: 'one', colors: ['Negro', 'Negro', 'Blanco', 'Azul marino', 'Beige', 'Verde'],
    images: ['gorra'],
    about: 'con cierre ajustable en la parte posterior',
  },
  {
    key: 'bufandas', family: 'accesorios', category: 'Accesorios de moda', weight: 3,
    types: ['Bufanda', 'Chalina'], genders: ['Mujer'],
    brands: ['Platanitos'],
    price: [19.9, 49.9], sizes: 'one', colors: ['Gris', 'Beige', 'Camel', 'Vino', 'Negro', 'Crema'],
    images: ['abrigo'],
    about: 'de tejido suave y abrigador',
  },

  // ---------------------------------------------------------- Otros departamentos
  {
    key: 'pelotas', family: 'deporte', category: 'Deportes y aire libre', weight: 3, department: 'Deportes y aire libre',
    types: ['Pelota de Fútbol', 'Pelota de Básquet', 'Pelota de Vóley'], genders: [], genderInName: false,
    brands: ['Adidas', 'Nike', 'Wilson', 'Umbro'],
    models: { Adidas: ['Starlancer', 'Tiro League'], Nike: ['Academy', 'Pitch'], Wilson: ['NBA DRV', 'Evolution', 'AVP Soft Play'], Umbro: ['Neo Swerve'] },
    price: [35.9, 179.9], sizes: 'one', colors: ['Blanco', 'Naranja', 'Amarillo', 'Multicolor'],
    images: ['pelota'],
    about: 'de tamaño oficial',
  },
  {
    key: 'fitness', family: 'deporte', category: 'Deportes y aire libre', weight: 4, department: 'Deportes y aire libre',
    types: ['Mat de Yoga', 'Set de Mancuernas', 'Banda de Resistencia', 'Cuerda para Saltar', 'Cinturón para Peso'], genders: [], genderInName: false,
    brands: ['Workout', 'Reebok', 'Adidas'],
    price: [24.9, 199.9], sizes: 'one', colors: ['Negro', 'Lila', 'Gris', 'Azul', 'Verde'],
    images: ['gym', 'yoga'],
    about: 'para entrenar en casa o en el gimnasio',
  },
  {
    key: 'natacion', family: 'deporte', category: 'Deportes y aire libre', weight: 3, department: 'Deportes y aire libre',
    types: ['Lentes de Natación', 'Gorro de Natación'], genders: ['Unisex', 'Niño', 'Juvenil'],
    brands: ['Speedo'],
    models: { Speedo: ['Mariner Pro', 'Vengeance', 'Plain Moulded Silicone', 'Pace'] },
    price: [39.9, 129.9], sizes: 'one', colors: ['Negro', 'Azul', 'Celeste', 'Rosado', 'Transparente'],
    images: ['tomatodo', 'gym'],
    about: 'cómodo y resistente al cloro',
  },
  {
    key: 'tomatodos', family: 'deporte', category: 'Tomatodos y loncheras', weight: 4, department: 'Deportes y aire libre',
    types: ['Tomatodo', 'Tomatodo con Caña', 'Botella Térmica', 'Lonchera Térmica'], genders: [], genderInName: false,
    brands: ['Scool', 'Flying Tiger', 'Nike', 'Adidas'],
    models: { Scool: ['450 ml Hello Kitty', '950 ml Neón', '600 ml Kuromi'], Nike: ['Fuel Jug 40 oz', 'Hypercharge 24 oz'], Adidas: ['Steel 0.75 L'] },
    price: [19.9, 109.9], sizes: 'one', colors: ['Negro', 'Rosado', 'Celeste', 'Lila', 'Verde', 'Blanco'],
    images: ['tomatodo'],
    about: 'libre de BPA y fácil de lavar',
  },
  {
    key: 'audifonos', family: 'tecnologia', category: 'Tecnología', weight: 5, department: 'Electrónica',
    types: ['Audífonos Inalámbricos', 'Audífonos Bluetooth On-Ear', 'Audífonos Deportivos'], genders: [], genderInName: false,
    brands: ['Lenovo', 'i2go', 'Kingmax'],
    models: { Lenovo: ['LP40 Pro', 'XT88', 'Thinkplus GM2 Pro', 'TH30'], i2go: ['Air Buds', 'Sound Pro'], Kingmax: ['KMH-##'] },
    price: [29.9, 199.9], sizes: 'one', colors: ['Negro', 'Blanco', 'Gris', 'Rosado', 'Azul'],
    images: ['audifonos1', 'audifonos2'],
    about: 'con Bluetooth 5.3 y estuche de carga',
  },
  {
    key: 'accesorios-tech', family: 'tecnologia', category: 'Tecnología', weight: 5, department: 'Electrónica',
    types: ['Cargador Portátil 10000 mAh', 'Cable USB-C a USB-C', 'Parlante Bluetooth', 'Mouse Inalámbrico', 'Cargador de Pared 20 W'], genders: [], genderInName: false,
    brands: ['i2go', 'Lenovo', 'Kingmax'],
    models: { Lenovo: ['Thinkplus', 'Legion'], i2go: ['Basic', 'Pro', 'Plus'] },
    price: [15.9, 149.9], sizes: 'one', colors: ['Negro', 'Blanco', 'Gris', 'Azul'],
    images: ['smartphone'],
    about: 'práctico para tu día a día',
  },
  {
    key: 'electrodomesticos', family: 'hogar', category: 'Electrodomésticos', weight: 6, department: 'Hogar y cocina',
    types: ['Licuadora', 'Hervidor Eléctrico', 'Plancha a Vapor', 'Freidora de Aire', 'Sandwichera', 'Purificador de Aire'], genders: [], genderInName: false,
    brands: ['Kingmax', 'Hush', 'Ichimatsu'],
    price: [59.9, 499.9], sizes: 'one', colors: ['Negro', 'Blanco', 'Plata', 'Rojo'],
    images: ['electro'],
    about: 'de bajo consumo con apagado automático',
  },
  {
    key: 'cocina', family: 'hogar', category: 'Cocina y mesa', weight: 6, department: 'Hogar y cocina',
    types: ['Set de Tazas', 'Juego de Vajilla 12 Piezas', 'Olla Antiadherente', 'Set de Cuchillos', 'Taza de Cerámica', 'Contenedores Herméticos'], genders: [], genderInName: false,
    brands: ['Ichimatsu', 'Flying Tiger', 'Tuhome'],
    price: [9.9, 199.9], sizes: 'one', colors: ['Blanco', 'Negro', 'Beige', 'Verde', 'Celeste', 'Multicolor'],
    images: ['cocina'],
    about: 'apto para microondas y lavavajillas',
  },
  {
    key: 'muebles', family: 'hogar', category: 'Muebles', weight: 5, department: 'Hogar y cocina',
    types: ['Escritorio', 'Rack para TV', 'Silla de Oficina', 'Velador', 'Sofá 3 Cuerpos'], genders: [], genderInName: false,
    brands: ['Tuhome'],
    models: { Tuhome: ['Essential', 'Keria Lite', 'Office 1', 'Nórdico', 'Terraza', 'Oslo'] },
    price: [149.9, 899.9], sizes: 'one', colors: ['Wengue', 'Blanco', 'Roble', 'Gris', 'Negro'],
    images: ['sofa', 'silla', 'sala'],
    about: 'fácil de armar, incluye instructivo',
  },
  {
    key: 'decoracion', family: 'hogar', category: 'Decoración', weight: 6, department: 'Hogar y cocina',
    types: ['Cojín Decorativo', 'Set de Portavelas', 'Cesta Multiusos', 'Lámpara de Mesa', 'Marco de Fotos', 'Florero'], genders: [], genderInName: false,
    brands: ['Flying Tiger', 'Tuhome', 'Platanitos Life'],
    price: [5.9, 129.9], sizes: 'one', colors: ['Beige', 'Blanco', 'Gris', 'Dorado', 'Verde', 'Terracota'],
    images: ['sala', 'lampara', 'dormitorio'],
    about: 'para darle un toque cálido a tus espacios',
  },
  {
    key: 'juguetes', family: 'juguetes', category: 'Juguetes y juegos', weight: 5, department: 'Juguetes y juegos',
    types: ['Rompecabezas 1000 Piezas', 'Lanzador de Agua', 'Set de Bloques', 'Peluche', 'Carro a Fricción', 'Gimnasio para Bebé'], genders: [], genderInName: false,
    brands: ['Fisher Price', 'X-Shot', 'Warner Bros', 'Flying Tiger'],
    models: { 'X-Shot': ['Excel Micro', 'Fast-Fill', 'Hyper Gel'], 'Fisher Price': ['Little People', 'Ríe y Aprende', 'Mega Bloks'] },
    price: [19.9, 199.9], sizes: 'one', colors: VARIOUS,
    images: ['juguetes'],
    about: 'recomendado para mayores de 3 años',
  },
  {
    key: 'juegos-mesa', family: 'juguetes', category: 'Juguetes y juegos', weight: 3, department: 'Juguetes y juegos',
    types: ['Juego de Mesa', 'Juego de Cartas', 'Rompecabezas 500 Piezas'], genders: [], genderInName: false,
    brands: ['Flying Tiger', 'Warner Bros'],
    price: [14.9, 129.9], sizes: 'one', colors: VARIOUS,
    images: ['juegoMesa'],
    about: 'para jugar en familia o con amigos',
  },
  {
    key: 'manga', family: 'libros', category: 'Libros y cómics', weight: 4, department: 'Libros',
    types: ['Manga'], genders: [], genderInName: false,
    brands: ['Panini'],
    models: { Panini: ['Dragon Ball Super N.%', 'One Piece N.%#', 'Chainsaw Man N.%', 'Frieren N.%', 'Jujutsu Kaisen N.%', 'Spy x Family N.%', 'Cells at Work N.%'] },
    price: [29.9, 59.9], sizes: 'one', colors: VARIOUS,
    images: ['libro'],
    about: 'tomo de colección de la serie',
  },
  {
    key: 'comics', family: 'libros', category: 'Libros y cómics', weight: 2, department: 'Libros',
    types: ['Cómic'], genders: [], genderInName: false,
    brands: ['Panini'],
    models: { Panini: ['Amazing Spider-Man N.%', 'Batman Vol. %', 'Daredevil Vol. %', 'X-Men N.%', 'Álbum Copa América 2028'] },
    price: [29.9, 59.9], sizes: 'one', colors: VARIOUS,
    images: ['libro'],
    about: 'edición de colección',
  },
  {
    key: 'utiles', family: 'utiles', category: 'Útiles y oficina', weight: 6, department: 'Oficina',
    types: ['Colores x 24', 'Plumones Punta Fina x 10', 'Cuaderno A4 Cuadriculado', 'Resaltadores x 6', 'Set de Lápices de Grafito', 'Agenda 2027'], genders: [], genderInName: false,
    brands: ['Faber-Castell', 'Stabilo', 'Flying Tiger', 'Scool'],
    models: { 'Faber-Castell': ['Ecolápiz', 'Grip 2001', 'Supersoft'], Stabilo: ['Boss Original', 'Point 88', 'Pen 68'] },
    price: [3.9, 69.9], sizes: 'one', colors: VARIOUS,
    images: ['cuaderno', 'plumones'],
    about: 'para tus apuntes y proyectos',
  },
  {
    key: 'maquillaje', family: 'belleza', category: 'Maquillaje', weight: 4, department: 'Belleza',
    types: ['Labial Líquido', 'Máscara de Pestañas', 'Base de Maquillaje', 'Brillo Labial', 'Set de Brochas'], genders: [], genderInName: false,
    brands: ['Maybelline', 'Flying Tiger'],
    models: { Maybelline: ['Superstay Vinyl Ink', 'Lifter Gloss', 'Sky High', 'Fit Me', 'Lash Sensational'] },
    price: [18.9, 89.9], sizes: 'one', colors: ['Rojo', 'Nude', 'Rosado', 'Negro', 'Coral', 'Vino'],
    images: ['labial', 'brochas'],
    about: 'de acabado profesional',
  },
  {
    key: 'cuidado-personal', family: 'belleza', category: 'Cuidado personal', weight: 4, department: 'Belleza',
    types: ['Shampoo', 'Acondicionador', 'Crema Facial Hidratante', 'Tinte Kit 2 Aplicaciones', 'Protector Solar FPS 50'], genders: [], genderInName: false,
    brands: ['Coquette', 'Be Natural', 'Platanitos Life'],
    price: [10.9, 89.9], sizes: 'one', colors: NO_COLOR,
    images: ['skincare', 'shampoo'],
    about: 'con ingredientes de origen natural',
  },
  {
    key: 'snacks', family: 'abarrotes', category: 'Snacks y abarrotes', weight: 5, department: 'Abarrotes',
    types: [''], genders: [], genderInName: false,
    brands: ['Lotte', 'Nongshim'],
    models: {
      Lotte: ['Galletas Pepero Original x 32 gr', 'Galletas Pepero Almond x 32 gr', 'Choco Pie x 12 und', 'Chicle Xylitol x 87 gr'],
      Nongshim: ['Fideos Shin Ramyun x 120 gr', 'Fideos Chapagetti x 140 gr', 'Snack Shrimp Crackers x 75 gr', 'Fideos Neoguri x 120 gr'],
    },
    price: [3.5, 29.9], sizes: 'one', colors: NO_COLOR,
    images: ['snacks'],
    about: 'el antojo perfecto',
  },
  {
    key: 'vinos', family: 'bebida', category: 'Vinos y licores', weight: 3, department: 'Vino',
    types: ['Vino Tinto', 'Vino Rosé', 'Vino Blanco'], genders: [], genderInName: false,
    brands: ['Tabernero'],
    models: { Tabernero: ['Borgoña 750 ml', 'Gran Tinto 750 ml', 'Semi Seco 750 ml', 'Malbec 750 ml', 'Fina Reserva 750 ml'] },
    price: [21.9, 89.9], sizes: 'one', colors: NO_COLOR,
    images: ['vino'],
    about: 'elaborado en el valle de Chincha',
  },
  {
    key: 'piscos', family: 'bebida', category: 'Vinos y licores', weight: 2, department: 'Vino',
    types: ['Pisco Quebranta', 'Pisco Acholado', 'Pisco Italia'], genders: [], genderInName: false,
    brands: ['La Caravedo', 'Tabernero'],
    models: { 'La Caravedo': ['Puro 750 ml', 'Mosto Verde 500 ml'], Tabernero: ['Reservado 750 ml', 'Clásico 700 ml'] },
    price: [39.9, 149.9], sizes: 'one', colors: NO_COLOR,
    images: ['licor'],
    about: 'destilado peruano con denominación de origen',
  },
  {
    key: 'bebes', family: 'bebes', category: 'Bebés', weight: 5, department: 'Bebés',
    types: ['Body Manga Larga', 'Set de Bodies x 3', 'Enterizo', 'Conjunto Recién Nacido'], genders: ['Bebé'],
    brands: ['Colloky', 'Platanitos Life'],
    price: [29.9, 99.9], sizes: 'baby', colors: ['Blanco', 'Celeste', 'Rosado', 'Amarillo', 'Crema', 'Multicolor'],
    images: ['bebe'],
    about: 'de algodón pima suave',
  },
  {
    key: 'equipaje', family: 'equipaje', category: 'Equipaje', weight: 4, department: 'Equipaje',
    types: ['Maleta de Cabina 20"', 'Maleta Mediana 24"', 'Neceser', 'Maletín de Viaje'], genders: [], genderInName: false,
    brands: ['Samsonite', 'Bubba Bags', 'Discovery Expedition'],
    models: { Samsonite: ['Spinner Uplite', 'Base Boost', 'Freeform'], 'Bubba Bags': ['Originals Matte', 'Bubbita'] },
    price: [55.9, 699.9], brandPrice: { 'Bubba Bags': [55.9, 149.9] }, sizes: 'one', colors: ['Negro', 'Azul marino', 'Gris', 'Rosado', 'Verde'],
    images: ['maleta'],
    about: 'resistente para tus viajes',
  },
  {
    key: 'mascotas', family: 'mascotas', category: 'Mascotas', weight: 3, department: 'Mascotas',
    types: ['Plato para Mascota', 'Collar para Perro', 'Juguete Mordedor', 'Cama para Mascota'], genders: [], genderInName: false,
    brands: ['Flying Tiger', 'Platanitos Life'],
    price: [9.9, 89.9], sizes: 'one', colors: ['Gris', 'Azul', 'Rosado', 'Verde', 'Beige'],
    images: ['mascotas'],
    about: 'para consentir a tu engreído',
  },
];

// Público → departamento de la tienda (para el resumen por departamento).
export const GENDER_DEPARTMENT = {
  Mujer: 'Mujeres',
  Hombre: 'Hombres',
  Unisex: 'Unisex (mujeres y hombres)',
  Niño: 'Niños',
  Niña: 'Niñas',
  Juvenil: 'Niños',
  Bebé: 'Bebés',
};
